In [9]:
import pandas as pd 

In [10]:
dt = {'Id':[11,12,13,14,15],
     'first_name':['A','B','C','D','E'],
     'company':['aa','bb','cc','dd','ee'],
     'address':['Hyd','Hyd','Hyd','Hyd','Hyd',]} 
mydt = pd.DataFrame(dt)

In [11]:
print(mydt)

   Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [21]:
import os
os.getcwd()

'C:\\Users\\student'

In [15]:
mydt.to_csv('Workingfile.csv',index = False)

### Reading the data from CSV File

In [18]:
mydata = pd.read_csv('WorkingFile.csv')

In [19]:
print(mydata)

   Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [8]:
pwd

'C:\\Users\\student'

### Print only Two Columns 
### Print the Large value from CustID column -- max
### Print the least value from CustID column -- min
### Average of CustdID column

In [23]:
import numpy as np

In [26]:
a1 = np.array([(1,2,3),4,5,6])
print(a1.shape)
a2 = np.array([(1,2),(2,3),(4,5)])
print(a2.shape)

(4,)
(3, 2)


In [29]:
a1 = np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]
